name: CD - SemVer

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, 'chore(release)') == false
    name: Release
    timeout-minutes: 10
    env:
      DRY_RUN: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release
        id: release
        uses: ridedott/release-me-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.semver_access_token }}
        with:
          dry-run: ${{ env.DRY_RUN }}
          release-branches: '["main"]'
          release-rules-append: |
            [
              { "release": "patch", "type": "chore" },
              { "release": "patch", "type": "ci" },
              { "release": "patch", "type": "refactor" },
              { "release": false, "subject": "*\\[skip release\\]*" }
            ]
      - uses: actions/checkout@v3
        if: steps.release.outputs.released == 'true' && env.DRY_RUN == 'false'
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Keep minor version updated
        if: steps.release.outputs.released == 'true' && env.DRY_RUN == 'false'
        run: |
          git push origin :refs/tags/'v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}'
          git tag 'v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}' --force
          git push --tags